### ISSUE TITLE
Project needs to be setup

### ISSUE THREAD

**Issue by andrewjrhill** [andrewjrhill/hygge-ui#1]
### Scope

The project needs to be setup so that we can get working on the UI library. 

### Steps to Complete

1. Create a new react application called `hygge-ui` using `create-react-app`.

2. Initialise a new git repository locally by running `git init` in your `hygge-ui` root directory.

3. Run `git remote add origin https://github.com/andrewjrhill/hygge-ui.git` to point your local repository to the remote repository on GitHub.

4. Setup your first commit by adding the files / folders in your `hygge-ui` root directory as an initial commit with `git add .` followed by `git commit -m "initial commit"`.

5. Finally; force-push your initial commit to the remote repository with `git push origin master -f`. It is important to note that you would normally never force push to the `master` branch as you might overwrite someone elses changes -- but this is setting up the projects first commit so it is acceptable.

**Comment by justineamber** [comment]
Project needs to be setup #1 has been completed.

**Comment by andrewjrhill** [comment]
Looks great 👏 well done.
